bedroom_choices = {
    '1' : 1,
    '2' : 2,
    '3' : 3,
    '4' : 4,
    '5' : 5,
    '6' : 6,
    '7' : 7,
    '8' : 8,
    '9' : 9,
    '10' : 10,

}

price_choices = {
    '100000' : '10,00,000',
    '200000' : '20,00,000',
    '300000' : '30,00,000',
    '400000' : '40,00,000',
    '500000' : '50,00,000',
    '600000' : '60,00,000',
    '700000' : '70,00,000',
    '800000' : '80,00,000',
    '900000' : '90,00,000',
    '1000000' : '100+ Crore',

}

state_choices = {
    'AP' : 'Andhra Pradesh(AP)',
    'AR' : 'Arunachal Pradesh(AR)',
    'AS' : 'Assam(AS)',
    'BR' : 'Bihar(BR)',
    'CG' : 'Chhattisgarh(CG)',
    'GA' : 'Goa(GA)',
    'GJ' : 'Gujarat(GJ)',
    'HR' : 'Haryana(HR)',
    'HP' : 'Himachal Pradesh(HP)',
    'JK' : 'Jammu and Kashmir(JK)',
    'JH' : 'Jharkhand(JH)',
    'KA' : 'Karnataka(KA)',
    'KL' : 'Kerala(KL)',
    'MP' : 'Madhya Pradesh(MP)',
    'MH' : 'Maharashtra(IL)',
    'MN' : 'Manipur(MN)',
    'ML' : 'Meghalaya(ML)',
    'MZ' : 'Mizoram(MZ)',
    'NL' : 'Nagaland(NL)',
    'OR' : 'Odisha(OR)',
    'PB' : 'Punjab(PB)',
    'RJ' : 'Rajasthan(RJ)',
    'SK' : 'Sikkim(SK)',
    'TN' : 'Tamil Nadu(TN)',
    'TG' : 'Telangana(TG)',
    'TR' : 'Tripura(TR)',
    'UP' : 'Uttar Pradesh(UP)',
    'UK' : 'Uttarakhand(UK)',
    'WB' : 'West Bengal(WB)',
    'AN' : 'Andaman and Nicobar Islands(AN)',
    'CH' : 'Chandigarh(CH)',
    'DH' : 'Dadra and Nagar Haveli(DH)',
    'DD' : 'Daman and Diu(DD)',
    'DL' : 'Delhi(DL)',
    'LD' : 'Lakshadweep(LD)',
    'PY' : 'Pondicherry(PY)',

}